### ISSUE TITLE
SSG For Docs

### ISSUE THREAD

**Issue by shadowtime2000** [eon-web/eon#10]
**Is your feature request related to a problem? Please describe.**
The current website uses `docsify` which renders the website on the fly (I think). The new website docs in the `rebrand` branch I believe uses hard coded written HTML which would become a little hard to maintain.

**Describe the solution you'd like**
Using an SSG to generate documentation from Markdown to make it easy to maintain documentation.

**Describe alternatives you've considered**
None.

**Additional context**
I would recommend Docusaurus v2 or Vuepress

**Comment by codemaster138** [comment]
I'm already building a new documentation site... Releasing soon

**Comment by codemaster138** [comment]
> The new website docs in the rebrand branch I believe uses hard coded written HTML which would become a little hard to maintain

Nope. I'm using my own custom static site generator [inert](github.com/codemaster138/inert) to build the site
