### ISSUE TITLE
[WIP] Feature: Middlewares

### ISSUE THREAD

**Issue by codemaster138** [eon-web/eon#2]
**Is your feature request related to a problem? Please describe.**
Currently, eon doesn't support middlewares like in express/connect/etc. Since there is already a vast range of existing middlewares, development would be much easier with middleware support.

**Describe the solution you'd like**
Middlewares like in express should be supported

**Describe alternatives you've considered**
—

**Additional context**
I'm working on it right now. Development builds can be downloaded using
```bash
npm i eonjs@beta
```

**Comment by codemaster138** [comment]
Already in progress!

**Comment by alexanderjanke** [comment]
I'd highly suggest you create a separate branch for these things so it's easier to keep track of what has happened.

Commits for middleware:
https://github.com/eon-web/eon/commit/428e786de093481cf4c399d2d884cd35a598ce17
https://github.com/eon-web/eon/commit/230a319150db2e47bf4f05fca71a3701ac56a634
https://github.com/eon-web/eon/commit/d085324f899f98d905a27fca923e76999f021cb5
https://github.com/eon-web/eon/commit/301e38882e35b397199b4541167aa31627dea924
https://github.com/eon-web/eon/commit/17027ce0cb0361a4650b1c8b2dbe0213fe0534be
https://github.com/eon-web/eon/commit/361870953c7e9fe59a4bdb17ed36f182a6443ba4
https://github.com/eon-web/eon/commit/45e994475edcc741e9b04352229eb03fc61307fe

Also when commiting you can refer to this issue by saying "#2 Fixed a typo" in the commit name - this auto refers to this issue so it's all linked up nicely.

**Comment by codemaster138** [comment]
@alexanderjanke Yeah... I was under a bit of time pressure... I'll change it now

**Comment by codemaster138** [comment]
@alexanderjanke moved to a new 'middlewares' branch and reset 'master' to the commit for the latest stable version on npm

**Comment by codemaster138** [comment]
PR #3 mostly fixes this issue. Since I'm not sure it works, I'll create a new `latest` version v1.16.0, but leave the `stable` tag with 1.15.0 for now. **If any problems arise, please reopen this issue**.
