### ISSUE TITLE
🚨 Content-Type header is not set

### ISSUE THREAD

**Issue by dotvirus** [eon-web/eon#5]
**Describe the bug**
When using app.json(), app.text(), the Content-Type header is not set

**To Reproduce**
```javascript
const eon = require("eonjs");

const app = eon(8080);

app.get("/").text((req, res) => {
  return "HELLO WORLD";
});

app.get("/:name").json((req, res) => {
  return { name: req.data.name };
});

app.listen(() => {
  console.log("Eon running");
});
```

**Expected behavior**
.json() applies `Content-Type: application/json`.
.text() applies `Content-Type: text/html`.

Preferably with `; charset=utf-8`.

Node 12.14

**Comment by codemaster138** [comment]
Thanks for reporting! I'll get to work immediately!
