### ISSUE TITLE
[WIP] Typescript Declarations

### ISSUE THREAD

**Issue by shadowtime2000** [eon-web/eon#7]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Typescript declarations so this framework can be used in Typescript

**Describe alternatives you've considered**
Rewriting the entire codebase in Typescript, but that may need more planning

**Additional context**
None.

**Comment by shadowtime2000** [comment]
Working on this in PR #8.

**Comment by codemaster138** [comment]
Your PR has been merged. I will now close this issue.

**Comment by codemaster138** [comment]
btw your changes will be released tomorrow (25th of October, 2020)
