### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by shadowtime2000** [eon-web/eon#9]
**Is your feature request related to a problem? Please describe.**
There are no tests that prove that Eon is functional.

**Describe the solution you'd like**
Unit tests with coverage reporting. (`supertest` for testing servers?)

**Describe alternatives you've considered**
None.

**Additional context**
I can take a go at this, just checking what everyone thinks.

**Comment by codemaster138** [comment]
@shadowtime2000 Great idea! I've been wanting to write unit tests for a while now but never had the time to do it. You can try it out if you want to because I don't think I'll have time to do it any time soon.

**Comment by shadowtime2000** [comment]
Great! I will start working on it.

**Comment by codemaster138** [comment]
How far away are you from completing this?

**Comment by codemaster138** [comment]
@shadowtime2000 BTW I made some changes, consider rebasing your branch off of [eon-web/eon](https://github.com/eon-web/eon/tree/master)

**Comment by shadowtime2000** [comment]
@codemaster138 I am pretty far away from completing this, if you want to take over, I can open a PR with my current tests.

**Comment by codemaster138** [comment]
@shadowtime2000 OK do that

**Comment by codemaster138** [comment]
Hey @shadowtime2000, thanks for creating your PR! I'll take over from there now
